name = "r2-access"
main = "src/index.ts"
compatibility_date = "2026-01-30"

[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "a11y-document-bucket"
preview_bucket_name = "a11y-docs-input-preview"

[[d1_databases]]
binding = "DB"
database_name = "a11y_doc_db"
database_id = "2be1e452-fe3a-4ab2-a04a-63b471e11afa"

[env.production]
vars = { ACCOUNT_ID = "YOUR_ACCOUNT_ID", BUCKET_NAME = "a11y-docs-input" }

[env.development]
vars = { ACCOUNT_ID = "YOUR_ACCOUNT_ID", BUCKET_NAME = "a11y-docs-input-preview" }

[build]
command = "npm run build"
